version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ./node_modules/.bin/eslint -v
      - run: npm show eslint-plugin-html version
      - run: ./node_modules/.bin/eslint ./
      - run: ./node_modules/.bin/stylelint -v
      - run: npm show stylelint-config-standard version
      - run: npm show postcss-html version
      - run: npm show @stylelint/postcss-css-in-js version
      - run: ./node_modules/.bin/stylelint ./**/*.css ./**/*.html ./**/*.js
