name: main
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm ls
      - run: ./node_modules/.bin/eslint ./
      - run: ./node_modules/.bin/stylelint ./**/*.css ./**/*.html ./**/*.js
